# Generated by Django 4.2.17 on 2024-12-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ar', 'Arabic')], default='en', max_length=10),
            preserve_default=False,
        ),
    ]
