# Generated by Django 4.2.17 on 2024-12-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ar', 'Arabic')], default='en', max_length=2),
        ),
    ]
