# Generated by Django 4.2.17 on 2025-01-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoAPI', '0002_remove_video_thumbnail_video_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
